### ISSUE TITLE
System.Exception: Instructions not found; unable to patch.

### ISSUE THREAD

**Issue by RunningDroid** [ExterminatorX99/BetterManaRegen#1]
This mod fails to load with the latest tModLoader 1.4 alpha (1.4.3.2+0.12-1.4-Alpha-714687ea45b42ef64ac66261cfce06ccc0cc8b76-5249449817591177834)

Trace:
```[16:46:15] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateManaRegen() modified by BetterManaRegenFixed
[16:46:15] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.Exception: Instructions not found; unable to patch. Sorry!
   at BetterManaRegenFixed.BetterManaRegenFixed.Player_UpdateManaRegen(ILContext ilContext) in BetterManaRegenFixed.cs:line 73
   at MonoMod.Cil.ILContext.Invoke(Manipulator manip)
   at MonoMod.RuntimeDetour.ILHook.Context.InvokeManipulator(MethodDefinition def, Manipulator cb)
   at MonoMod.RuntimeDetour.ILHook.Context.Refresh()
   at MonoMod.RuntimeDetour.ILHook.Apply()
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator, ILHookConfig& config)
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator, ILHookConfig config)
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._NewILHook(MethodBase from, Manipulator to)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._Add[TDelegate](Func`3 gen, TDelegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint.Modify(Delegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify(MethodBase method, Delegate callback)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify[T](MethodBase method, Delegate callback)
   at IL.Terraria.Player.add_UpdateManaRegen(Manipulator )
   at Terraria.ModLoader.ModContent.<>c.<Load>b__41_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 303
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 358
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 297
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 134
   at Terraria.ModLoader.ModLoader.<>c__DisplayClass45_0.<BeginLoad>b__0() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 114
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

[16:46:15] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading BetterManaRegenFixed
The mod(s) have been automatically disabled.
System.Exception: Instructions not found; unable to patch. Sorry!
   at BetterManaRegenFixed.BetterManaRegenFixed.Player_UpdateManaRegen(ILContext ilContext) in BetterManaRegenFixed.cs:line 73
   at MonoMod.Cil.ILContext.Invoke(Manipulator manip)
   at MonoMod.RuntimeDetour.ILHook.Context.InvokeManipulator(MethodDefinition def, Manipulator cb)
   at MonoMod.RuntimeDetour.ILHook.Context.Refresh()
   at MonoMod.RuntimeDetour.ILHook.Apply()
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator, ILHookConfig& config)
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator, ILHookConfig config)
   at MonoMod.RuntimeDetour.ILHook..ctor(MethodBase from, Manipulator manipulator)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._NewILHook(MethodBase from, Manipulator to)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint._Add[TDelegate](Func`3 gen, TDelegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpoint.Modify(Delegate hookDelegate)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify(MethodBase method, Delegate callback)
   at MonoMod.RuntimeDetour.HookGen.HookEndpointManager.Modify[T](MethodBase method, Delegate callback)
   at IL.Terraria.Player.add_UpdateManaRegen(Manipulator )
   at Terraria.ModLoader.ModContent.<>c.<Load>b__41_0(Mod mod) in tModLoader\Terraria\ModLoader\ModContent.cs:line 303
   at Terraria.ModLoader.ModContent.LoadModContent(CancellationToken token, Action`1 loadAction) in tModLoader\Terraria\ModLoader\ModContent.cs:line 358
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 297
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 134
[16:46:15] [.NET ThreadPool Worker/INFO] [tML]: Disabling Mod: BetterManaRegenFixed
```

[client.log](https://gist.github.com/RunningDroid/aa47c185884d82d5a00403758fa872f3)

**Comment by RunningDroid** [comment]
Fixed in latest release on Steam Workshop: https://steamcommunity.com/sharedfiles/filedetails/?id=2577536543
